pom.xml

Solucionado un error en las dependencias del pom.xml que hacía que el proyecto no utilizase el css.

Fix: Actualización de pom.xml

---

src/main/java/org/springframework/samples/petclinic/model/Intolerancias.java
src/main/java/org/springframework/samples/petclinic/model/Producto.java
src/main/java/org/springframework/samples/petclinic/model/Tienda.java
src/main/resources/import.sql

tienda y producto, tambien se ha solucionado el problema con las
intolerancias.

Fix: Se ha solucionado problemas de relaciones entre las entidades

---

.github/workflows/maven-build.yml

Eliminados los tests unitarios del archivo ya que se realizan con maven build

Fix: Borrar tests

---

src/main/webapp/WEB-INF/jsp/tiendas/tiendaDetails.jsp

Vista de los detalles de una tienda

Vista Tienda Details

---

src/main/java/org/springframework/samples/localizer/model/Intolerancias.java
src/main/webapp/WEB-INF/jsp/productos/productoDetails.jsp

Creada la vista de producto

---

src/main/java/org/springframework/samples/localizer/model/Intolerancias.java
src/main/java/org/springframework/samples/localizer/model/Producto.java

Solucionado error en la relación múltiple entre intolerancias y productos

---

src/main/webapp/WEB-INF/jsp/productos/productosList.jsp

Se arreglan los errores encontrados

Fix: Vista de Lista de productos

---

src/test/java/org/springframework/samples/localizer/service/TiendaServiceTests.java

Arreglado los test del servicio de Tienda

Fix-TiendaServiceTest

---

src/main/java/org/springframework/samples/localizer/web/TiendaController.java

Fix: Actualizado Tienda Controller

---

src/main/java/org/springframework/samples/localizer/repository/TiendaRepository.java
src/main/java/org/springframework/samples/localizer/service/TiendaService.java
src/main/java/org/springframework/samples/localizer/web/TiendaController.java
src/main/less/petclinic.less
src/main/webapp/WEB-INF/jsp/tiendas/tiendaDetails.jsp

Feat: Vista de los productos de una tienda con filtro

Feat: Vista de los productos de una tienda con filtro 

---

src/main/java/org/springframework/samples/localizer/web/TiendaController.java
src/main/java/org/springframework/samples/localizer/web/UserController.java
src/main/webapp/WEB-INF/jsp/users/createOrUpdateUserForm.jsp
src/main/webapp/WEB-INF/tags/menu.tag

Creación del registro y la vista. Faltan dar autoridad para poder
completarlo.

Feat: Registro implementado.

---

src/main/webapp/WEB-INF/jsp/productos/productoDetails.jsp

Se cambia ${producto.verificado} por ${producto.estado=='ACEPTADO'}

Fix: productoDetails - Estado

---

src/main/less/petclinic.less
src/main/webapp/WEB-INF/jsp/productos/createOrUpdateProductoForm.jsp
src/main/webapp/WEB-INF/jsp/productos/productosVerificar.jsp

Formulario completo para crear, actualizar, validad y rechazar productos.

Feat: Formulario para validación de productos

---

src/main/webapp/WEB-INF/jsp/productos/createOrUpdateProductoForm.jsp

Fix: Vista Update Producto

---

src/main/webapp/WEB-INF/jsp/reservas/reservasList.jsp

Se ha hecho un prototipo a falta de los controladores necesarios. Más
tarde se modificará una vez éstos están hechos y se pueda probar su
funcionamiento.

Feat: Formulario de historial de reservas

---

src/main/webapp/WEB-INF/jsp/reservas/createOrUpdateReservaForm.jsp

Feat: Formulario de reserva

---

src/main/webapp/WEB-INF/jsp/productos/productoDetails.jsp
src/main/webapp/WEB-INF/jsp/tiendas/tiendaDetails.jsp

Fix estilo botones

---

src/main/java/org/springframework/samples/localizer/model/Producto.java

(falta validar el atributo motivo)

Feat: añadidas validaciones de productos

---

src/main/webapp/WEB-INF/jsp/productos/productoDetails.jsp

Se añade auth para que no puedan reservar sin estar registrado

Fix: Botones de Producto Details

---

src/main/java/org/springframework/samples/localizer/web/CheckoutController.java
src/main/less/petclinic.less
src/main/webapp/WEB-INF/jsp/pago/pagoForm.jsp
src/main/webapp/WEB-INF/jsp/pago/pagoResult.jsp
src/main/webapp/WEB-INF/jsp/paypal/cancel.jsp
src/main/webapp/WEB-INF/jsp/paypal/payForm.jsp
src/main/webapp/WEB-INF/jsp/paypal/success.jsp

Feat: Vistas Pago

---

.github/workflows/maven-build.yml

Fix: Actualizar workflow

---

src/main/webapp/WEB-INF/jsp/productos/productoDetails.jsp
src/main/webapp/WEB-INF/jsp/productos/productosList.jsp
src/main/webapp/WEB-INF/jsp/tiendas/tiendaDetails.jsp

Se modifica el filtro para que cuando se elija Vegetariano se añadan los productos Veganos.

Fix: filtro productos vegetariano

---

src/main/java/org/springframework/samples/localizer/model/Estado.java
src/main/java/org/springframework/samples/localizer/model/Reserva.java
src/main/java/org/springframework/samples/localizer/web/ReservaController.java
src/main/less/petclinic.less
src/main/resources/import.sql
src/main/webapp/WEB-INF/jsp/productos/productoDetails.jsp
src/main/webapp/WEB-INF/jsp/reservas/createOrUpdateReservaForm.jsp
src/main/webapp/WEB-INF/jsp/reservas/reservasList.jsp
src/test/java/org/springframework/samples/localizer/service/ReservaServiceTest.java

Incluye un nuevo ESTADO y estilos del formulario

Feat: Estilos historial reservas

---

src/main/webapp/WEB-INF/jsp/productos/productoDetails.jsp

Se ha arreglado el botón de editar un producto desde la vista detallada
de otro

Fix-BotonEditarProducto: COmpleted

---

src/main/java/org/springframework/samples/localizer/model/Reserva.java
src/main/java/org/springframework/samples/localizer/repository/ProductoRepository.java
src/main/java/org/springframework/samples/localizer/service/ProductoService.java
src/main/java/org/springframework/samples/localizer/service/TiendaService.java
src/main/java/org/springframework/samples/localizer/web/ReservaController.java
src/main/resources/import.sql
src/main/webapp/WEB-INF/jsp/productos/productoDetails.jsp
src/test/java/org/springframework/samples/localizer/model/ReservaTest.java
src/test/java/org/springframework/samples/localizer/service/ReservaServiceTest.java

+ Se ha puesto el precio total de una reserva como propiedad derivada,
para que se calcule correctamente al actualizar un producto

Se han arreglado algunos errores

---

src/main/java/org/springframework/samples/localizer/DBConfig.java
src/main/webapp/WEB-INF/jsp/productos/productoDetails.jsp
src/main/webapp/WEB-INF/jsp/productos/productosList.jsp
src/main/webapp/WEB-INF/jsp/tiendas/tiendaDetails.jsp

Paginacion para paginas tiendaDetails y productoDetails

Feat paginacion

---

src/main/webapp/WEB-INF/jsp/productos/productoDetails.jsp
src/main/webapp/WEB-INF/jsp/tiendas/tiendaDetails.jsp

Quitar paginacion de paginas tiendaDetails y productoDetails

Quitar paginacion de las paginas tiendaDetails y productoDetails

---

src/main/java/org/springframework/samples/localizer/web/TiendaController.java

Solucionado el error que te mandaba a una página de error, al buscar
tiendas sin poner nada en el buscador.

Solucionado el error al buscar tiendas

---

src/test/java/org/springframework/samples/localizer/model/ReservaTest.java
src/test/java/org/springframework/samples/localizer/web/UserControllerTests.java

Fix test controladores
